name: Yarn Package Check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * 0'
  workflow_dispatch:

jobs:
  outdated-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Outdated Versions
        id: outdated-versions
        run: npm run depends > ./outdated_versions.md
        
      - if: ${{ success() }}
        name: Create issue from file
        id: broken-link-report
        uses: peter-evans/create-issue-from-file@b4f9ee0a9d4abbfc6986601d9b1a4f8f8e74c77e
        with:
          token: ${{ secrets.github_token }}

          title: "Dependencies are out of date"
          content-filepath: ./outdated_versions.md
          repository: ${{ env.GITHUB_ACTION_REPOSITORY }}