name: Yarn Package Check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * 0'
  workflow_dispatch:

jobs:
  outdated-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Outdated Versions
        id: outdated-versions
        run: |
          echo 'DEP_OUTPUT<<EOF' >> $GITHUB_ENV
          npm run depends >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        
      - if: ${{ success() }}
        name: Create issue from file
        id: broken-link-report
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Dependencies are outdated
          token: ${{secrets.GITHUB_TOKEN}}
          labels: depend
          body: ${{env.DEP_OUTPUT}}
        